### PR TITLE
chore: update fastify to ^5.0.0

### PR DESCRIPTION
**Pull request by Fdawgs**
See  https://github.com/fastify/fastify/issues/5694

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
@Fdawgs can you take a look why this is failing? Also we can disable package-manager-ci or figure out why it is failing?

**Comment by gurgunday** [comment]
```sh
 types/index.test-d.ts:21:0
  ✖  21:0  Parameter type (opts?: PrettyOptions | undefined) => PrettyStream is declared too wide for argument type typeof PinoPretty.  

  1 error
```

**Comment by Fdawgs** [comment]
Thanks @gurgunday, I find spotting errors in Tap output a nightmare!

**Comment by Fdawgs** [comment]
@fastify/typescript 

ihave-2831941345

**Comment by mcollina** [comment]
please remove package manager CI

**Comment by Fdawgs** [comment]
> please remove package manager CI

Done.

As @gurgunday raised in a comment before, CI is failing due to a TypeScript type issue, but my TypeScript knowledge is amateur at best so no idea how to solve it.

**Comment by simoneb** [comment]
I created a PR that uses this branch as the base, to fix the ts issue and migrate to Node's test runner. there's a test failure though, which seems legitimate, about the addresses that the server is listening on, and I suspect it's related to the Node.js version. I find confirmation of that when spinning up a Fastify server in my Node repl, it's only listening on the IPV6 address:

image

**Comment by simoneb** [comment]
In all honesty the I'm not entirely confident about the fix I did for the tsd failure, as my TS knowledge is fairly limited as well. I can't really bother with TS idiosincrasies.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
